name: sean-smith-info 
services:
- build_command: npm build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: stratzenblitz/sean-smith-info 
  name: sean-smith-info 
